include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = eBayFixerPrefs
eBayFixerPrefs_FILES = EBRootController.m
eBayFixerPrefs_FRAMEWORKS = UIKit
eBayFixerPrefs_PRIVATE_FRAMEWORKS = Preferences
eBayFixerPrefs_INSTALL_PATH = /Library/PreferenceBundles
eBayFixerPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
